apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus3.fullname" . }}
  labels:
    {{- include "nexus3.labels" . | nindent 4 }}
  annotations: 
    {{- with .Values.service.annotations }}
      {{- toYaml . | nindent 6}}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
      - port: {{ .port }}
        protocol: {{ .protocol }}
        targetPort: {{ .targetPort }}
        name: {{ .name }}
    {{- end }}
  selector:
    {{- include "nexus3.selectorLabels" . | nindent 4 }}
