{{- if .Values.volumeMountsConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.volumeMountsConfig.name }}
  labels:
    {{- if .Values.volumeMountsConfig.additionalLabels }}
      {{- toYaml .Values.volumeMountsConfig.additionalLabels | nindent 4 }}
    {{- end }}

data:
{{ .Values.volumeMountsConfig.fileName | indent 2 }}: |-
{{ .Values.volumeMountsConfig.fileContent | indent 4 }}
{{- end }}
