{{- if .Values.volumeMountsScript.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.volumeMountsScript.name }}
  labels:
    {{- if .Values.volumeMountsScript.additionalLabels }}
      {{- toYaml .Values.volumeMountsScript.additionalLabels | nindent 4 }}
    {{- end }}

data:
{{ .Values.volumeMountsScript.fileName | indent 2 }}: |-
{{ .Values.volumeMountsScript.fileContent | indent 4 }}
{{- end }}