apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "postgres.name" . }}
  labels:
    app: {{ template "postgres.name" . }}
    chart: {{ template "postgres.chart" . }}
spec:
  serviceName: {{ .Values.serviceName }}
  replicas: {{ .Values.replicas }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
  selector:
    matchLabels:
      app: {{ template "postgres.name" . }}
  template:
    metadata:
      name: {{ template "postgres.name" . }}
      labels:
        app: {{ template "postgres.name" . }}
    spec:
      containers:
        - name: {{ template "postgres.fullname" . }}
          image: {{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.secrets.postgresdb_password }}
            - name: PGDATA
              value: {{ .Values.secrets.pg_data }}
          volumeMounts:
            - name: postgres-disk
              mountPath: {{ .Values.volumeMounts.postgres_disk }}
      volumes:
        - hostPath:
            path: {{ .Values.hostPath }}
            type: DirectoryOrCreate
          name: postgres-disk  
