apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mantis-api-server.fullname" . }}
  labels:
    {{- include "mantis-api-server.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}