apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.imagePullSecrets.name }}-{{ .Release.Name }}"
  labels:
    {{- include "mantis-backend.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}