apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: htpasswd
  namespace: mantis-system
data:
  auth: bWFudGlzOiRhcHIxJEVtMGFmQ2d4JE5hVG9WZkFqRWRZQ2ZIZ1ZXb2xKTS8K ## decoded user: mantis, pass: mantis@0987