apiVersion: v1
kind: Service
metadata:
  name: {{ include "ample-postgeres.name" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ template "ample-postgeres.name" . }}
