apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{ .Values.service.apps }}
  ports:
      {{- range .Values.service.ports}}
        - port: {{ .port }}
          targetPort: {{ .targetPort }}
          protocol: TCP
          name: {{ .name }}
      {{- end }}
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}

